version: '3'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  staging.cord.network:
    image: dhiway/cord:develop
    ports:
      - 9944:9944
    restart: always
    command:
      - --dev
      - --unsafe-rpc-external
      - --unsafe-ws-external

  graphql-engine:
    image: onfinality/subql-query:v0.11.0
    ports:
      - 3001:3000
    depends_on:
      - "postgres"
      - "staging.cord.network"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=cord
      - --playground

  subquery-node:
    image: onfinality/subql-node:v0.27.1-0
    depends_on:
      - "postgres"
      - "staging.cord.network"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - .:/app
    command:
      - -f=/app
      - --subquery-name=cord
      - --migrate

