specVersion: "0.0.1"
description: "This subquery indexes which block a given extrinsic is finalized in"
repository: "https://github.com/subquery/subql-examples"

schema: "./schema.graphql"

network:
  endpoint: "wss://staging.cord.network"
  types: {
    "AccountInfo": "AccountInfoWithTripleRefCount",
    "Address": "MultiAddress",
    "AmountOf": "i128",
    "Balance": "u128",
    "LookupSource": "MultiAddress",
    "IdentifierOf": "Text",
    "IdOf": "Hash",
    "HashOf": "Hash",
    "StatusOf": "bool",
    "StreamDetails": {
      "hash": "HashOf",
      "cid": "Option<IdentifierOf>",
      "parent_cid": "Option<IdentifierOf>",
      "schema": "Option<IdOf>",
      "link": "Option<IdOf>",
      "creator": "CordAccountOf",
      "block": "BlockNumber",
      "revoked": "StatusOf"
    },
    "StreamCommit": {
      "hash": "HashOf",
      "cid": "Option<IdentifierOf>",
      "block": "BlockNumber",
      "commit": "StreamCommitOf"
    },
    "StreamCommitOf": {
      "_enum": ["Create", "Update", "Status"]
    },
    "StreamLink": {
      "identifier": "IdOf",
      "creator": "CordAccountOf"
    },
    "SchemaDetails": {
      "hash": "HashOf",
      "cid": "Option<IdentifierOf>",
      "parent_cid": "Option<IdentifierOf>",
      "creator": "CordAccountOf",
      "block": "BlockNumber",
      "permissioned": "StatusOf",
      "revoked": "StatusOf"
    },
    "SchemaCommit": {
      "hash": "HashOf",
      "cid": "Option<IdentifierOf>",
      "block": "BlockNumber",
      "commit": "SchemaCommitOf"
    },
    "SchemaCommitOf": {
      "_enum": [
        "Genesis",
        "Update",
        "Delegate",
        "RevokeDelegation",
        "Permission",
        "Status"
      ]
    },
    "RegistrarDetails": {
      "block": "BlockNumber",
      "revoked": "bool"
    },
    "TxVerifiedOf": {
      "tx_hash": "HashOf",
      "ptx_verified": "bool"
    },
    "CordAccountOf": "AccountId",
    "DidIdentifierOf": "AccountId",
    "AccountIdentifierOf": "AccountId",
    "NixAccount": "AccountId",
    "BlockNumberOf": "BlockNumber"
  }

dataSources:
  - name: runtime
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
